// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: moment.proto

package fatRank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	"time"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalMomentList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PersonalMoment `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PersonalMomentList) Reset() {
	*x = PersonalMomentList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalMomentList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalMomentList) ProtoMessage() {}

func (x *PersonalMomentList) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalMomentList.ProtoReflect.Descriptor instead.
func (*PersonalMomentList) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalMomentList) GetItems() []*PersonalMoment {
	if x != nil {
		return x.Items
	}
	return nil
}

type PersonalMoment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;column:id"`
	// @gotags: gorm:"column:person_id"
	PersonId int64 `protobuf:"varint,2,opt,name=personId,proto3" json:"personId,omitempty" gorm:"column:person_id"`
	// @gotags: gorm:"column:created_time"
	CreatedTime time.Time `protobuf:"bytes,3,opt,name=createdTime,proto3" json:"createdTime,omitempty" gorm:"column:created_time"`
	// @gotags: gorm:"column:content"
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty" gorm:"column:content"`
	// @gotags: gorm:"column:fatrate"
	Fatrate float32 `protobuf:"fixed32,5,opt,name=fatrate,proto3" json:"fatrate,omitempty" gorm:"column:fatrate"`
	// @gotags: gorm:"column:visible"
	Visible bool `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty" gorm:"column:visible"`
}
func(PersonalMoment)TableName()string{
	return "person_moment"
}
func (x *PersonalMoment) Reset() {
	*x = PersonalMoment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_moment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalMoment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalMoment) ProtoMessage() {}

func (x *PersonalMoment) ProtoReflect() protoreflect.Message {
	mi := &file_moment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalMoment.ProtoReflect.Descriptor instead.
func (*PersonalMoment) Descriptor() ([]byte, []int) {
	return file_moment_proto_rawDescGZIP(), []int{1}
}

func (x *PersonalMoment) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonalMoment) GetPersonId() int64 {
	if x != nil {
		return x.PersonId
	}
	return 0
}

func (x *PersonalMoment) GetCreatedTime() time.Time {
	if x != nil {
		return x.CreatedTime
	}
	return time.Time{}
}

func (x *PersonalMoment) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PersonalMoment) GetFatrate() float32 {
	if x != nil {
		return x.Fatrate
	}
	return 0
}

func (x *PersonalMoment) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

var File_moment_proto protoreflect.FileDescriptor

var file_moment_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07,
	0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x12, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x2d,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c,
	0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0xc8, 0x01,
	0x0a, 0x0e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x4d, 0x6f, 0x6d, 0x65, 0x6e, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x0b,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x74, 0x72, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x07, 0x66, 0x61, 0x74, 0x72, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x76, 0x69, 0x73, 0x69, 0x62, 0x6c, 0x65, 0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_moment_proto_rawDescOnce sync.Once
	file_moment_proto_rawDescData = file_moment_proto_rawDesc
)

func file_moment_proto_rawDescGZIP() []byte {
	file_moment_proto_rawDescOnce.Do(func() {
		file_moment_proto_rawDescData = protoimpl.X.CompressGZIP(file_moment_proto_rawDescData)
	})
	return file_moment_proto_rawDescData
}

var file_moment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_moment_proto_goTypes = []interface{}{
	(*PersonalMomentList)(nil),    // 0: fatRank.PersonalMomentList
	(*PersonalMoment)(nil),        // 1: fatRank.PersonalMoment
	(*time.Time)(nil), // 2: google.protobuf.Timestamp
}
var file_moment_proto_depIdxs = []int32{
	1, // 0: fatRank.PersonalMomentList.items:type_name -> fatRank.PersonalMoment
	2, // 1: fatRank.PersonalMoment.createdTime:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_moment_proto_init() }
func file_moment_proto_init() {
	if File_moment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_moment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalMomentList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_moment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalMoment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_moment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_moment_proto_goTypes,
		DependencyIndexes: file_moment_proto_depIdxs,
		MessageInfos:      file_moment_proto_msgTypes,
	}.Build()
	File_moment_proto = out.File
	file_moment_proto_rawDesc = nil
	file_moment_proto_goTypes = nil
	file_moment_proto_depIdxs = nil
}
