// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.22.0
// source: personInfo.proto

package fatRank

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PersonalInformationList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*PersonalInformation `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *PersonalInformationList) Reset() {
	*x = PersonalInformationList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalInformationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInformationList) ProtoMessage() {}

func (x *PersonalInformationList) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInformationList.ProtoReflect.Descriptor instead.
func (*PersonalInformationList) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{0}
}

func (x *PersonalInformationList) GetItems() []*PersonalInformation {
	if x != nil {
		return x.Items
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Null) Reset() {
	*x = Null{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{1}
}

type PersonalInformation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: gorm:"primaryKey;column:id"
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// @gotags: gorm:"column:name"
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// @gotags: gorm:"column:sex"
	Sex string `protobuf:"bytes,3,opt,name=sex,proto3" json:"sex,omitempty"`
	// @gotags: gorm:"column:tall"
	Tall float32 `protobuf:"fixed32,4,opt,name=tall,proto3" json:"tall,omitempty"`
	// @gotags: gorm:"column:weight"
	Weight float32 `protobuf:"fixed32,5,opt,name=weight,proto3" json:"weight,omitempty"`
	// @gotags: gorm:"column:age"
	Age int64 `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *PersonalInformation) Reset() {
	*x = PersonalInformation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInformation) ProtoMessage() {}

func (x *PersonalInformation) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInformation.ProtoReflect.Descriptor instead.
func (*PersonalInformation) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{2}
}

func (x *PersonalInformation) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PersonalInformation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInformation) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *PersonalInformation) GetTall() float32 {
	if x != nil {
		return x.Tall
	}
	return 0
}

func (x *PersonalInformation) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *PersonalInformation) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

type PersonalInformationFatRate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FatRate float32 `protobuf:"fixed32,2,opt,name=fatRate,proto3" json:"fatRate,omitempty"`
}

func (x *PersonalInformationFatRate) Reset() {
	*x = PersonalInformationFatRate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalInformationFatRate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInformationFatRate) ProtoMessage() {}

func (x *PersonalInformationFatRate) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInformationFatRate.ProtoReflect.Descriptor instead.
func (*PersonalInformationFatRate) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{3}
}

func (x *PersonalInformationFatRate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonalInformationFatRate) GetFatRate() float32 {
	if x != nil {
		return x.FatRate
	}
	return 0
}

type PersonalRanks struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PersonalRanks []*PersonRank `protobuf:"bytes,1,rep,name=personalRanks,proto3" json:"personalRanks,omitempty"`
}

func (x *PersonalRanks) Reset() {
	*x = PersonalRanks{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalRanks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalRanks) ProtoMessage() {}

func (x *PersonalRanks) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalRanks.ProtoReflect.Descriptor instead.
func (*PersonalRanks) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{4}
}

func (x *PersonalRanks) GetPersonalRanks() []*PersonRank {
	if x != nil {
		return x.PersonalRanks
	}
	return nil
}

type PersonRank struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Sex  string                      `protobuf:"bytes,2,opt,name=sex,proto3" json:"sex,omitempty"`
	Pr   *PersonalInformationFatRate `protobuf:"bytes,3,opt,name=pr,proto3" json:"pr,omitempty"`
}

func (x *PersonRank) Reset() {
	*x = PersonRank{}
	if protoimpl.UnsafeEnabled {
		mi := &file_personInfo_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonRank) ProtoMessage() {}

func (x *PersonRank) ProtoReflect() protoreflect.Message {
	mi := &file_personInfo_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonRank.ProtoReflect.Descriptor instead.
func (*PersonRank) Descriptor() ([]byte, []int) {
	return file_personInfo_proto_rawDescGZIP(), []int{5}
}

func (x *PersonRank) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PersonRank) GetSex() string {
	if x != nil {
		return x.Sex
	}
	return ""
}

func (x *PersonRank) GetPr() *PersonalInformationFatRate {
	if x != nil {
		return x.Pr
	}
	return nil
}

var File_personInfo_proto protoreflect.FileDescriptor

var file_personInfo_proto_rawDesc = []byte{
	0x0a, 0x10, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x07, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x22, 0x4d, 0x0a, 0x17, 0x50,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x06, 0x0a, 0x04, 0x6e, 0x75,
	0x6c, 0x6c, 0x22, 0x89, 0x01, 0x0a, 0x13, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10,
	0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x61, 0x6c, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x04,
	0x74, 0x61, 0x6c, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x67, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x4a,
	0x0a, 0x1a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x18, 0x0a, 0x07, 0x66, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x02, 0x52, 0x07, 0x66, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x22, 0x4a, 0x0a, 0x0d, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x12, 0x39, 0x0a, 0x0d, 0x70,
	0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x52, 0x61, 0x6e, 0x6b, 0x52, 0x0d, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x67, 0x0a, 0x0a, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x61, 0x6e, 0x6b, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x33, 0x0a, 0x02, 0x70, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b,
	0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x46, 0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x52, 0x02, 0x70, 0x72, 0x32,
	0xae, 0x03, 0x0a, 0x0b, 0x52, 0x61, 0x6e, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12,
	0x48, 0x0a, 0x08, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x12, 0x1c, 0x2e, 0x66, 0x61,
	0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1c, 0x2e, 0x66, 0x61, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x12, 0x4d, 0x0a, 0x06, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x23, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x46,
	0x61, 0x74, 0x52, 0x61, 0x74, 0x65, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x05, 0x47, 0x65, 0x74, 0x46,
	0x52, 0x12, 0x1c, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a,
	0x13, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x52, 0x61, 0x6e, 0x6b, 0x22, 0x00, 0x12, 0x31, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x54, 0x6f, 0x70,
	0x12, 0x0d, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x6e, 0x75, 0x6c, 0x6c, 0x1a,
	0x16, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e,
	0x61, 0x6c, 0x52, 0x61, 0x6e, 0x6b, 0x73, 0x22, 0x00, 0x12, 0x54, 0x0a, 0x0e, 0x52, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x12, 0x1c, 0x2e, 0x66, 0x61,
	0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x20, 0x2e, 0x66, 0x61, 0x74, 0x52,
	0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x28, 0x01, 0x12,
	0x3f, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x73, 0x12,
	0x0d, 0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x6e, 0x75, 0x6c, 0x6c, 0x1a, 0x1c,
	0x2e, 0x66, 0x61, 0x74, 0x52, 0x61, 0x6e, 0x6b, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x00, 0x30, 0x01,
	0x42, 0x03, 0x5a, 0x01, 0x2e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_personInfo_proto_rawDescOnce sync.Once
	file_personInfo_proto_rawDescData = file_personInfo_proto_rawDesc
)

func file_personInfo_proto_rawDescGZIP() []byte {
	file_personInfo_proto_rawDescOnce.Do(func() {
		file_personInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_personInfo_proto_rawDescData)
	})
	return file_personInfo_proto_rawDescData
}

var file_personInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_personInfo_proto_goTypes = []interface{}{
	(*PersonalInformationList)(nil),    // 0: fatRank.PersonalInformationList
	(*Null)(nil),                       // 1: fatRank.null
	(*PersonalInformation)(nil),        // 2: fatRank.PersonalInformation
	(*PersonalInformationFatRate)(nil), // 3: fatRank.PersonalInformationFatRate
	(*PersonalRanks)(nil),              // 4: fatRank.PersonalRanks
	(*PersonRank)(nil),                 // 5: fatRank.PersonRank
}
var file_personInfo_proto_depIdxs = []int32{
	2, // 0: fatRank.PersonalInformationList.items:type_name -> fatRank.PersonalInformation
	5, // 1: fatRank.PersonalRanks.personalRanks:type_name -> fatRank.PersonRank
	3, // 2: fatRank.PersonRank.pr:type_name -> fatRank.PersonalInformationFatRate
	2, // 3: fatRank.RankService.Register:input_type -> fatRank.PersonalInformation
	2, // 4: fatRank.RankService.Update:input_type -> fatRank.PersonalInformation
	2, // 5: fatRank.RankService.GetFR:input_type -> fatRank.PersonalInformation
	1, // 6: fatRank.RankService.GetTop:input_type -> fatRank.null
	2, // 7: fatRank.RankService.RegisterPerson:input_type -> fatRank.PersonalInformation
	1, // 8: fatRank.RankService.WatchPersons:input_type -> fatRank.null
	2, // 9: fatRank.RankService.Register:output_type -> fatRank.PersonalInformation
	3, // 10: fatRank.RankService.Update:output_type -> fatRank.PersonalInformationFatRate
	5, // 11: fatRank.RankService.GetFR:output_type -> fatRank.PersonRank
	4, // 12: fatRank.RankService.GetTop:output_type -> fatRank.PersonalRanks
	0, // 13: fatRank.RankService.RegisterPerson:output_type -> fatRank.PersonalInformationList
	2, // 14: fatRank.RankService.WatchPersons:output_type -> fatRank.PersonalInformation
	9, // [9:15] is the sub-list for method output_type
	3, // [3:9] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_personInfo_proto_init() }
func file_personInfo_proto_init() {
	if File_personInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_personInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalInformationList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Null); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalInformation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalInformationFatRate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalRanks); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_personInfo_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonRank); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_personInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_personInfo_proto_goTypes,
		DependencyIndexes: file_personInfo_proto_depIdxs,
		MessageInfos:      file_personInfo_proto_msgTypes,
	}.Build()
	File_personInfo_proto = out.File
	file_personInfo_proto_rawDesc = nil
	file_personInfo_proto_goTypes = nil
	file_personInfo_proto_depIdxs = nil
}
